- name: Playbook-line-in-file.yaml
  hosts: localhost
  tasks:
    - name: Create file2
      lineinfile:
        dest: /tmp/file2
        line: "{{ item }}"
        with_items:
          - "This is line 1"
          - "This is line 2"
