- name: Add lines to a file
  hosts: localhost
  tasks:
    - name: Create file
      file:
        path: /tmp/file2
        state: touch

    - name: Add lines to file
      lineinfile:
        path: /tmp/file2
        line: "{{ item }}"
      with_items:
        - "This is line 1"
        - "This is line 2"
